theme: jekyll-theme-midnight
name: White Paper

#markdown: kramdown
#kramdown:
#    input: GFM

url: https://2n2b1.github.io/makefiletutorial/
description: Makefile Tutorial by Example
syntax-highlighting:
    enabled: true
    css: syntax.css
highlighter: pygments

# Owner/author information
owner:
  name: Chase Lambert
