name: White Paper
markdown: kramdown
kramdown:
    input: GFM
url: http://vimsheet.com
description: A Great Vim Cheat Sheet
syntax-highlighting:
    enabled: true
    css: syntax.css

# Owner/author information
owner:
  name: Chase Lambert

